### ISSUE TITLE
Terraform INIT failing with azure Devops self hosted agent on ACI

### ISSUE THREAD

**Issue by Tajjun** [Azure/terraform-azurerm-aci-devops-agent#13]
I have 2 terraform pipelines in azure devops:

1- provisions vnet and azure container instance and registers it as an agent pool node.
2- uses the self hosted agent pool which uses the aci from the first pipeline to provision other stuff.

The second pipeline fails when it reaches init with the following message:

`##[error]Terraform command 'init' failed with exit code '1'.:  Failed to get existing workspaces: containers.Client#ListBlobs: Failure sending request: StatusCode=0 -- Original Error: Get "https://xxx.blob.core.windows.net/terraform?comp=list&prefix=xxx-infra-dev.tfstateenv%253A&restype=container": dial tcp xx.xxx.xx.x:443: connect: connection timed out
`

this how I provision the ACI (I removed some parts from)

```
terraform {
  required_version = "~> 0.13"
  backend "azurerm" {}
}
provider "azurerm" {
  version                    = "~> 2.8.0"
  skip_provider_registration = true
  features {}
}


module "aci-devops-agent" {
  source                   = "Azure/aci-devops-agent/azurerm"
  resource_group_name      = var.resource_group_name
  location                 = var.location
  enable_vnet_integration  = true
  create_resource_group    = false
  vnet_resource_group_name = var.resource_group_name
  vnet_name                = local.virtual_network_name
  subnet_name              = data.azurerm_subnet.subnet["mgmt"].name

  linux_agents_configuration = {
    agent_name_prefix = "aci-${var.environment}-${var.app_name}"
    agent_pool_name   = var.agent_pool_name
    count             = 1,
    docker_image      = "jcorioland/aci-devops-agent"
    docker_tag        = "0.2-linux"
    cpu               = 1
    memory            = 4
  }

  azure_devops_org_name              = "xxx"
  azure_devops_personal_access_token = var.pat

}
```

and the agent is successfully detected in azure devops

![image](https://user-images.githubusercontent.com/31044336/101880401-244a1c00-3b93-11eb-9f56-e6050907daa5.png)

**Comment by mozts2005** [comment]
what version of terraform CLI are you using?

**Comment by Tajjun** [comment]
0.13.5

**Comment by Tajjun** [comment]
@mozts2005 @jcorioland do you think I should open the ticket with terraform or azure ?

**Comment by julie-ng** [comment]
Hi Taj,

to help debug this and confirm the ACI agent does have network access to the storage account, can you please:

1. Go into the storage account with the TF state file, create a temporary text hello world text file, e.g. `hello.txt` in a separate container, e.g. `debugging-aci`.
2. Ensure the file is private. Then generate a short lived SAS token for the file and copy the "Blob SAS URL"
3. Grab a shell inside your network isolated self-hosted ACI agent via the Azure Portal
4. Try to access the temporary hello world text file.

```
curl https://<STORAGE_ACCOUNT_NAME>.blob.core.windows.net/debuging-aci/hello.txt?sp=r&st=2020-12<REST_OF_SAS_TOKEN>
```

Note: I chose to use a dummy text file to avoid outputting sensitive information from the state file. If you want to check the state file, use the `-o state-delete-me.txt` flag to avoid outputting it to the logs. And be sure to delete it afterwards.

Can you confirm the curl works?

**Comment by Tajjun** [comment]
Thanks @julie-ng for your tip I actually found the problem from the logs file in the aci.

 **solution:** 
was to re-create the PAT token in ADO.


**Troubleshooting steps:**
checked `/azp/agent/_diag/Agent_xxx-utc.log` and i saw 401 error message:

```
[2020-12-13 07:47:36Z INFO RSAFileKeyManager] Loading RSA key parameters from file /azp/agent/.credentials_rsaparams
[2020-12-13 07:47:36Z INFO VisualStudioServices] AAD Correlation ID for this token request: Unknown
[2020-12-13 08:09:17Z INFO MessageListener] No message retrieved from session 'xxx' within last 30 minutes.
[2020-12-13 08:39:17Z INFO MessageListener] No message retrieved from session 'xxx' within last 30 minutes.
[2020-12-13 08:42:37Z WARN VisualStudioServices] Authentication failed with status code 401.
```
and then recreated the PAT and it worked fine.

**Notes:**
- The terraform error message was misleading since it was dial `tcp xx.xxx.xx.x:443: connect: connection timed out`
- the new PAT token was created exactly like the old token, I have no idea why the new one worked and the old one didn't.

Thanks for the support.
