### ISSUE TITLE
Remove provider.tf file as we do not pass the subscription as ENV variable

### ISSUE THREAD

**Issue by aakash-pinc** [Azure/terraform-azurerm-aci-devops-agent#15]
Since we do not pass the subscription ID as an environment variable, we are getting the below error.
```
Error building AzureRM Client: 1 error occurred:
	* A Subscription ID must be configured when authenticating as a Service Principal using a Client Secret.
  on .terraform/modules/agent.aci-devops-agent/provider.tf line 1, in provider "azurerm":
   1: provider "azurerm" {
```
   
   Could you please make the subscription ID as an optional one?
```
provider "azurerm" {
  subscription_id= var.ARM_SUBSCRIPTION_ID ? var.ARM_SUBSCRIPTION_ID : <ENV variable for subscriptionid>
  features {}
}
```

**Comment by jcorioland** [comment]
Hi @aakashceg001 - thanks for opening this issue. Can you be a bit more specific ? How do you specify the subscription you are working with if you don't pass it? Thanks

**Comment by jcorioland** [comment]
closing because no more details. Feel free to reopen if needed @aakash-pinc.
