### ISSUE TITLE
Update README: Windows container cannot be added to vNets

### ISSUE THREAD

**Issue by james-flynn-ie** [Azure/terraform-azurerm-aci-devops-agent#17]
Windows containers cannot be added to container groups within vNets at present (https://docs.microsoft.com/en-us/azure/container-instances/container-instances-virtual-network-concepts#other-limitations).

It would be useful to include this in the README, as it cost me some time to implement the module before receiving the error message that Windows containers arent supported yet

**Comment by james-flynn-ie** [comment]
#16 addresses this issue.

**Comment by jcorioland** [comment]
Hi @james-flynn-ie thanks for reaching out. I just did a review of your PR. Let me know what you think. Thanks!

**Comment by james-flynn-ie** [comment]
Thanks @jcorioland I've committed your suggestions now, they look good to me. :+1:

**Comment by jcorioland** [comment]
Merged! Thanks for your contribution @james-flynn-ie!
