### ISSUE TITLE
Hide azure_devops_personal_access_token output when running `terraform plan` ❓ 

### ISSUE THREAD

**Issue by DavyGuedes** [Azure/terraform-azurerm-aci-devops-agent#19]
Hi,
How can I hide confidential information from the Azure DevOps token that is displayed when executing the `terraform plan`?

```hcl
  + resource "azurerm_container_group" "linux-container-group" {
      + fqdn                = (known after apply)
      + id                  = (known after apply)
      + ip_address          = (known after apply)
[...]

      + container {
          + commands              = (known after apply)
          + cpu                   = 1
          + environment_variables = {
              + "AZP_AGENT_NAME" = "..."
              + "AZP_POOL"       = "..."
              + "AZP_TOKEN"      = "TOKEN as plain text" # sensitive data
```

**Comment by DavyGuedes** [comment]
(I'm using azurerm_key_vault_secret module to retrieve the token at run time.)

**Comment by DavyGuedes** [comment]
I saw now that this feature is in the 7f100c1, but it is not yet available in the released versions.

**Comment by soccerjoshj07** [comment]
I believe using terraform 0.15.x brings in this functionality:
![image](https://user-images.githubusercontent.com/19912012/116284096-50d18f80-a752-11eb-8f47-19ba3acab3bb.png)
