### ISSUE TITLE
Readme fix

### ISSUE THREAD

**Issue by vasudev007** [Azure/terraform-azurerm-aci-devops-agent#20]
While passing external resources such as resource group and other services, the create resource flag should be set to false

  "create_resource_group    = false"

**Comment by jcorioland** [comment]
Hi @vasudev007, thank you for reporting an issue. Could you be a bit more specific about what issue you have encountered and what you would add in the README (and where), please? Thanks

**Comment by jcorioland** [comment]
closing because not answered.
feel free to reopen @vasudev007.
