### ISSUE TITLE
Windows Agents not appearing in DevOps agent pool

### ISSUE THREAD

**Issue by petercharleston** [Azure/terraform-azurerm-aci-devops-agent#21]
Hi there,

I have build Windows containers and pushed to ACR ok
The Terraform files build and the ACI's are running.
But the agents are not appearing in the Azure DevOps Agent pool

My Terraform Code:

module "aci-devops-agent" {
  source                = "Azure/aci-devops-agent/azurerm"
  resource_group_name   = "rg-aci-devops"
  location              = "uksouth"
  create_resource_group = true

  enable_vnet_integration  = false

    windows_agents_configuration = {
    agent_name_prefix = "windows-agent"
    agent_pool_name   = "Azure_Docker_Pool_TestLabs"
    count             = 2,
    docker_image      = "acrnewasm.azurecr.io/servercore"
    docker_tag        = "v1"
    cpu               = 1
    memory            = 4
  }
  
  azure_devops_org_name              = "ORGNAME"
  azure_devops_personal_access_token = "PATTOKEN"
}

**Comment by soccerjoshj07** [comment]
What's your docker image look like? At least for Linux, I did not have luck following the dockerfile in this repository and instead used the dockerfile and script here: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker

Perhaps try testing with this one and see if that works (the Linux one worked for me, at least):

Image: jcorioland/aci-devops-agent
Tag: 0.2-win

**Comment by jcorioland** [comment]
Hi @petercharleston! Have you been able to solve your issue? As suggested by @soccerjoshj07 (thanks!) you should not reuse the Dockerfile from this repository. They are just sample but are not updated on a regular basis. The documentation link pointed by @soccerjoshj07 is the one to follow.
Please let us know if you have been able to resolve your issue and if this ticket can be closed.
Thank you!

**Comment by jcorioland** [comment]
Assuming you've solved your issue @petercharleston, otherwise, feel free to reopen with details so we can help you! Thanks.
