### ISSUE TITLE
Does this work with Docker-in-Docker in ACI?

### ISSUE THREAD

**Issue by tlrh314** [Azure/terraform-azurerm-aci-devops-agent#26]
Does this module work with docker-in-docker for a self-hosted agent running in Azure Container Instances?

**Comment by jcorioland** [comment]
@tlrh314 this scenario has not been tested. Can you be a bit more specific about what you are expecting to do, please? I am curious about it :) thanks!

**Comment by tlrh314** [comment]
@jcorioland the idea was to deploy a self-hosted agent with Azure Container Instances (ACI) that has support for `docker build`, `docker push`, etc. So the requirement would be to have Docker-in-Docker (DinD), i.e. to install `docker` in the image that runs the agent and to bind-mount the Docker daemon socket from ACI into the agent container. Unfortunately ACI does not allow the latter, so I don't see a way to implement DinD support in ACI.

**Comment by jcorioland** [comment]
Indeed! For build and push tasks in pipeline, I would recommend to look/use [ACR tasks](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-quickstart-task-cli)

**Comment by tlrh314** [comment]
> Indeed! For build and push tasks in pipeline, I would recommend to look/use [ACR tasks](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-quickstart-task-cli)

Wow, this is amazing! This eliminates need for DinD alltogether as build is offloaded to Azure PaaS Magic Fairy Land by ACR. Very neat - thanks for pointing me to the ACR tasks @jcorioland !
