### ISSUE TITLE
Docker Image fails to start

### ISSUE THREAD

**Issue by clbarrett** [Azure/terraform-azurerm-aci-devops-agent#34]
I am using the provided Dockerfile and am getting this error when I try and run the image both locally and in the container.

exec ./start.sh: no such file or directory

Any idea what's going on here?  And how to fix it?

**Comment by clbarrett** [comment]
Thanks for the link.  I've bookmarked it.

This is what I get when I run the command with my own org details filled for the AZP_...

![image](https://user-images.githubusercontent.com/107525011/174067005-772f8de7-e5cc-4485-ac59-e4db4cfc1376.png)

**Comment by jcorioland** [comment]
that works for me from Git Bash too:
<img width="747" alt="image" src="https://user-images.githubusercontent.com/4435138/174068799-a51a0991-3d86-4894-89d4-7c23776067d8.png">

Any chance you can try to rebuild the Docker image? And maybe try on another machine just to double check ?
What Docker version are you using? Here's mine:

```console
Client: Docker Engine - Community
 Cloud integration: v1.0.24
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:48:21 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:46:14 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by clbarrett** [comment]
In a weird turn of events... my problem was line endings.  One of my editors must've given windows style (\r\n) line endings to the start.sh file.  Once I restored them back to Linux style (\n) it worked.  Thanks for the speedy help.
