### ISSUE TITLE
  Docker in Docker

### ISSUE THREAD

**Issue by clbarrett** [Azure/terraform-azurerm-aci-devops-agent#35]
I'm trying to replace some build agents that another company was hosting for us.  As they are no longer hosting said build agents for us I'm working on replacing them.  I was able to get up to the point of building on the agent when I got this error message:

##[error]Unhandled: Unable to locate executable file: 'docker'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

In researching it appears to be that I need to run some form of docker.sock.  But I'm not seeing how to do that with an ACI.  Is there any way to do this?  Either with this module or otherwise?

**Comment by jcorioland** [comment]
Hi @clbarrett - as far as I know, running docker in docker is not available for Azure Container Instance, for security reasons. This is not something that can be addressed in this Terraform module, unfortunately.

If your need is to be able to run pipelines that build/push docker images from the ACI agents, then I would recommend having a look at ACR Tasks that you can trigger from the DevOps agents: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-overview

Hope this helps!

*I am closing this issue, but feel free to reopen if you think I missed something. Thanks*

**Comment by clbarrett** [comment]
> Hi @clbarrett - as far as I know, running docker in docker is not available for Azure Container Instance, for security reasons. This is not something that can be addressed in this Terraform module, unfortunately.
> 
> If your need is to be able to run pipelines that build/push docker images from the ACI agents, then I would recommend having a look at ACR Tasks that you can trigger from the DevOps agents: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-overview
> 
> Hope this helps!
> 
> _I am closing this issue, but feel free to reopen if you think I missed something. Thanks_

Thanks.  I was afraid of that so I figured out another way to do what I need.  Your module was quite easy to use though.  And I greatly appreciate the link.
