### ISSUE TITLE
Issues with creating Azure Devops agent

### ISSUE THREAD

**Issue by krynn1** [Azure/terraform-azurerm-aci-devops-agent#7]
When using your module I get this error

_Error: Error building AzureRM Client: 1 error occurred:
	* A Subscription ID must be configured when authenticating as a Service Principal using a Client Secret.
  on .terraform/modules/aci-devops-agent/terraform-azurerm-aci-devops-agent-0.9/provider.tf line 1, in provider "azurerm":
   _1: provider "azurerm" {__

Also my devops project is https://%projectname%.visualstudio.com/ wouldn't this cause an issue for your 

So I tried to create the container based off your main.tf but I'm getting this error when trying to pull the image, I'm not sure if I'm configuring it wrong.

_t C:\azp\start.ps1:32 char:14
+ ...  $package = Invoke-RestMethod -Headers @{Authorization=("Basic $base6 ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:Htt 
   pWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe 
   ll.Commands.InvokeRestMethodCommand
Cannot index into a null array.
At C:\azp\start.ps1:33 char:3
+   $packageUrl = $package[0].Value.downloadUrl
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray_
 

2. Downloading and installing Azure Pipelines agent...
Exception calling "DownloadFile" with "2" argument(s): "Value cannot be null.
Parameter name: address"
At C:\azp\start.ps1:40 char:36
+   $wc.DownloadFile($packageUrl, "$(Get-Location)\agent.zip")
+                                    ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException
 
Expand-Archive : The path 'agent.zip' either does not exist or is not a valid 
file system path.
At C:\azp\start.ps1:42 char:3
+   Expand-Archive -Path "agent.zip" -DestinationPath "\azp\agent"
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (agent.zip:String) [Expand-Arch 
   ive], InvalidOperationException
    + FullyQualifiedErrorId : ArchiveCmdletPathNotFound,Expand-Archive
 
3. Configuring Azure Pipelines agent...
Cleanup. Removing Azure Pipelines agent...
.\config.cmd : The term '.\config.cmd' is not recognized as the name of a 
cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.
At C:\azp\start.ps1:68 char:5
+     .\config.cmd remove --unattended `
+     ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\config.cmd:String) [], Comman 
   dNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
.\config.cmd : The term '.\config.cmd' is not recognized as the name of a 
cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.
At C:\azp\start.ps1:48 char:5
+     .\config.cmd --unattended `
+     ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\config.cmd:String) [], Comman 
   dNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by krynn1** [comment]
I think my issues lie in the Currently only Linux containers can be deployed to virtual networkswhen I try to get the below working.  
resource "azurerm_network_profile" "windows_network_profile" {

  name                = "${var.env_shortname}${var.fo_location}-np"
  location            = var.location
  resource_group_name = azurerm_resource_group.devops_rg.name

  container_network_interface {
    name = "${local.env_name}-devops-${var.env_shortname}"

    ip_configuration {
      name      = "devops"
      subnet_id = azurerm_subnet.mgmt_devops.id
    }
  }
}

**Comment by jcorioland** [comment]
Hey sorry, I missed the notification on this one. Could you please share the terraform code you use to deploy the module?
What kind of authentication are you using for Terraform? It looks like you are using a service principal, if yes, are you specifying a value for `ARM_SUBSCRIPTION_ID` too? (see: https://www.terraform.io/docs/providers/azurerm/guides/service_principal_client_secret.html#configuring-the-service-principal-in-terraform).

Are you using the Docker image set in example or did you build your own one? If you did build your own one, can you share the Dockerfile, please?

Thanks

**Comment by krynn1** [comment]
Yeah that should work. We ended up going a different route with this. Didn't need to isolate the agent pool anymore. We can close this
